### PR TITLE
TOFT edits and gitignore

### PR DESCRIPTION
**Pull request by dreyjo**
Edited TOFT service copies requirements, added /extensions to gitignore, and added language on example packages to main file and packaging page.

### CODE REVIEW

**Comment by dreyjo** [comment]
[Add extensions folder to gitignore](https://trello.com/c/u6wGEeZA/57-add-extensions-folder-to-gitignore)

**Comment by nkrabben** [comment]
I don't think gitignore was updated in the first commit. I'm doing similar work in #18 so you don't need to adjust this, but just as a heads up.

**Comment by arhonemus** [comment]
[Create child pages of Specs by program displaying package examples](https://trello.com/c/eBhUAscO/49-create-child-pages-of-specs-by-program-displaying-package-examples)

**Comment by arhonemus** [comment]
[review and merge PR #17](https://trello.com/c/08q82q6M/58-review-and-merge-pr-17)

**Pull request merged**
